### ISSUE TITLE
Running init on first install fails

### ISSUE THREAD

**Issue by netgroover** [jotyGill/openpyn-nordvpn#33]
Running init on Raspbian Jessie following first install fails?

sudo -H pip3 install openpyn --upgrade
Downloading/unpacking openpyn
  Downloading openpyn-1.5.2.tar.gz (40kB): 40kB downloaded
  Running setup.py (path:/tmp/pip-build-oo5oujjn/openpyn/setup.py) egg_info for package openpyn
    
    warning: no files found matching 'README'
Downloading/unpacking requests from https://pypi.python.org/packages/5a/58/671011e3ff4a06e2969322267d78dcfda1bf4d1576551df1cce93cd7239d/requests-2.18.1-py2.py3-none-any.whl#md5=a7fbdc82134a2610b3d0cdc7e59f0bde (from openpyn)
  Downloading requests-2.18.1-py2.py3-none-any.whl (88kB): 88kB downloaded
Downloading/unpacking certifi>=2017.4.17 (from requests->openpyn)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB): 375kB downloaded
Downloading/unpacking urllib3>=1.21.1,<1.22 (from requests->openpyn)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB): 131kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests->openpyn)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Downloading/unpacking idna>=2.5,<2.6 (from requests->openpyn)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
Installing collected packages: openpyn, requests, certifi, urllib3, chardet, idna
  Running setup.py install for openpyn
    
    warning: no files found matching 'README'
    Installing openpyn-start-management script to /usr/local/bin
    Installing openpyn-management script to /usr/local/bin
    Installing openpyn script to /usr/local/bin
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: urllib3 1.9.1
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: chardet 2.3.0
    Not uninstalling chardet at /usr/lib/python3/dist-packages, owned by OS
Successfully installed openpyn requests certifi urllib3 chardet idna
Cleaning up...

sudo openpyn --init
Storing credentials in '/usr/share/openpyn/credentials with openvpn compatible 'auth-user-pass' file format

Enter your username for NordVPN, i.e youremail@yourmail.com: xxx@xxx.com
Enter the password for NordVPN: xxx
Traceback (most recent call last):
  File "/usr/local/bin/openpyn", line 9, in <module>
    load_entry_point('openpyn==1.5.2', 'console_scripts', 'openpyn')()
  File "/usr/local/lib/python3.4/dist-packages/openpyn/openpyn.py", line 110, in main
    args.tor_over_vpn, args.anti_ddos, args.test)
  File "/usr/local/lib/python3.4/dist-packages/openpyn/openpyn.py", line 124, in run
    initialise()
  File "/usr/local/lib/python3.4/dist-packages/openpyn/openpyn.py", line 212, in initialise
    credentials.save_credentials()
  File "/usr/local/lib/python3.4/dist-packages/openpyn/credentials.py", line 30, in save_credentials
    subprocess.run("sudo touch /usr/share/openpyn/credentials".split())
AttributeError: 'module' object has no attribute 'run'

**Comment by jotyGill** [comment]
The "subprocess.run()" was introduced in python 3.5, I should have made it clear that 3.5 is required, well now I have. Jessie still comes with 3.4 so need to install 3.5 or 3.6
You could use pyenv, to install it see.
https://github.com/pyenv/pyenv
https://github.com/pyenv/pyenv-installer
or this might be helpful.
https://jpcassidy.com/software/2016/11/29/python3-debian-jessie.html

**Comment by jotyGill** [comment]
I was trying the compilation method, well my pi is still compiling after couple hours lol. I am thinking of creating a new branch that would support 3.4 and maybe if that works fine, I'll later merge it to the main one.

**Comment by netgroover** [comment]
Yeah I thought it was a version issue of some sort, let me know how you get on with the compile on 3.4, I know it can take a while! Thanks.

**Comment by jotyGill** [comment]
That installation didn't complete as my Pi's os needs to be re-installed anyway, so I didn't bother. However I have created a new branch with 3.4 compatible code (well sort of, desktop notifications won't work). I have tested it on another Pi, it works! Hope you find it useful. Cheers.

**Comment by netgroover** [comment]
Great, thanks
